version: '3'
services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
