version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build: ./api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
